// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/derfinlay/basecrm/ent/customer"
	"github.com/derfinlay/basecrm/ent/login"
	"github.com/derfinlay/basecrm/ent/user"
)

// Customer is the model entity for the Customer schema.
type Customer struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Gender holds the value of the "gender" field.
	Gender customer.Gender `json:"gender,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CustomerQuery when eager-loading is set.
	Edges               CustomerEdges `json:"edges"`
	customer_created_by *int
	selectValues        sql.SelectValues
}

// CustomerEdges holds the relations/edges for other nodes in the graph.
type CustomerEdges struct {
	// Orders holds the value of the orders edge.
	Orders []*Order `json:"orders,omitempty"`
	// BillingAddresses holds the value of the billing_addresses edge.
	BillingAddresses []*BillingAddress `json:"billing_addresses,omitempty"`
	// DeliveryAddresses holds the value of the delivery_addresses edge.
	DeliveryAddresses []*DeliveryAddress `json:"delivery_addresses,omitempty"`
	// Tels holds the value of the tels edge.
	Tels []*Tel `json:"tels,omitempty"`
	// CreatedBy holds the value of the created_by edge.
	CreatedBy *User `json:"created_by,omitempty"`
	// Notes holds the value of the notes edge.
	Notes []*Note `json:"notes,omitempty"`
	// Login holds the value of the login edge.
	Login *Login `json:"login,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// OrdersOrErr returns the Orders value or an error if the edge
// was not loaded in eager-loading.
func (e CustomerEdges) OrdersOrErr() ([]*Order, error) {
	if e.loadedTypes[0] {
		return e.Orders, nil
	}
	return nil, &NotLoadedError{edge: "orders"}
}

// BillingAddressesOrErr returns the BillingAddresses value or an error if the edge
// was not loaded in eager-loading.
func (e CustomerEdges) BillingAddressesOrErr() ([]*BillingAddress, error) {
	if e.loadedTypes[1] {
		return e.BillingAddresses, nil
	}
	return nil, &NotLoadedError{edge: "billing_addresses"}
}

// DeliveryAddressesOrErr returns the DeliveryAddresses value or an error if the edge
// was not loaded in eager-loading.
func (e CustomerEdges) DeliveryAddressesOrErr() ([]*DeliveryAddress, error) {
	if e.loadedTypes[2] {
		return e.DeliveryAddresses, nil
	}
	return nil, &NotLoadedError{edge: "delivery_addresses"}
}

// TelsOrErr returns the Tels value or an error if the edge
// was not loaded in eager-loading.
func (e CustomerEdges) TelsOrErr() ([]*Tel, error) {
	if e.loadedTypes[3] {
		return e.Tels, nil
	}
	return nil, &NotLoadedError{edge: "tels"}
}

// CreatedByOrErr returns the CreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CustomerEdges) CreatedByOrErr() (*User, error) {
	if e.loadedTypes[4] {
		if e.CreatedBy == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.CreatedBy, nil
	}
	return nil, &NotLoadedError{edge: "created_by"}
}

// NotesOrErr returns the Notes value or an error if the edge
// was not loaded in eager-loading.
func (e CustomerEdges) NotesOrErr() ([]*Note, error) {
	if e.loadedTypes[5] {
		return e.Notes, nil
	}
	return nil, &NotLoadedError{edge: "notes"}
}

// LoginOrErr returns the Login value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CustomerEdges) LoginOrErr() (*Login, error) {
	if e.loadedTypes[6] {
		if e.Login == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: login.Label}
		}
		return e.Login, nil
	}
	return nil, &NotLoadedError{edge: "login"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Customer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case customer.FieldID:
			values[i] = new(sql.NullInt64)
		case customer.FieldName, customer.FieldGender:
			values[i] = new(sql.NullString)
		case customer.FieldCreatedAt, customer.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case customer.ForeignKeys[0]: // customer_created_by
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Customer fields.
func (c *Customer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case customer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case customer.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				c.Name = value.String
			}
		case customer.FieldGender:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gender", values[i])
			} else if value.Valid {
				c.Gender = customer.Gender(value.String)
			}
		case customer.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				c.CreatedAt = value.Time
			}
		case customer.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				c.UpdatedAt = value.Time
			}
		case customer.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field customer_created_by", value)
			} else if value.Valid {
				c.customer_created_by = new(int)
				*c.customer_created_by = int(value.Int64)
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Customer.
// This includes values selected through modifiers, order, etc.
func (c *Customer) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// QueryOrders queries the "orders" edge of the Customer entity.
func (c *Customer) QueryOrders() *OrderQuery {
	return NewCustomerClient(c.config).QueryOrders(c)
}

// QueryBillingAddresses queries the "billing_addresses" edge of the Customer entity.
func (c *Customer) QueryBillingAddresses() *BillingAddressQuery {
	return NewCustomerClient(c.config).QueryBillingAddresses(c)
}

// QueryDeliveryAddresses queries the "delivery_addresses" edge of the Customer entity.
func (c *Customer) QueryDeliveryAddresses() *DeliveryAddressQuery {
	return NewCustomerClient(c.config).QueryDeliveryAddresses(c)
}

// QueryTels queries the "tels" edge of the Customer entity.
func (c *Customer) QueryTels() *TelQuery {
	return NewCustomerClient(c.config).QueryTels(c)
}

// QueryCreatedBy queries the "created_by" edge of the Customer entity.
func (c *Customer) QueryCreatedBy() *UserQuery {
	return NewCustomerClient(c.config).QueryCreatedBy(c)
}

// QueryNotes queries the "notes" edge of the Customer entity.
func (c *Customer) QueryNotes() *NoteQuery {
	return NewCustomerClient(c.config).QueryNotes(c)
}

// QueryLogin queries the "login" edge of the Customer entity.
func (c *Customer) QueryLogin() *LoginQuery {
	return NewCustomerClient(c.config).QueryLogin(c)
}

// Update returns a builder for updating this Customer.
// Note that you need to call Customer.Unwrap() before calling this method if this Customer
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Customer) Update() *CustomerUpdateOne {
	return NewCustomerClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Customer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Customer) Unwrap() *Customer {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Customer is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Customer) String() string {
	var builder strings.Builder
	builder.WriteString("Customer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("name=")
	builder.WriteString(c.Name)
	builder.WriteString(", ")
	builder.WriteString("gender=")
	builder.WriteString(fmt.Sprintf("%v", c.Gender))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(c.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(c.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Customers is a parsable slice of Customer.
type Customers []*Customer
