// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/derfinlay/basecrm/ent/login"
	"github.com/derfinlay/basecrm/ent/loginreset"
	"github.com/derfinlay/basecrm/ent/note"
	"github.com/derfinlay/basecrm/ent/predicate"
)

// LoginResetQuery is the builder for querying LoginReset entities.
type LoginResetQuery struct {
	config
	ctx        *QueryContext
	order      []loginreset.OrderOption
	inters     []Interceptor
	predicates []predicate.LoginReset
	withNotes  *NoteQuery
	withLogin  *LoginQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LoginResetQuery builder.
func (lrq *LoginResetQuery) Where(ps ...predicate.LoginReset) *LoginResetQuery {
	lrq.predicates = append(lrq.predicates, ps...)
	return lrq
}

// Limit the number of records to be returned by this query.
func (lrq *LoginResetQuery) Limit(limit int) *LoginResetQuery {
	lrq.ctx.Limit = &limit
	return lrq
}

// Offset to start from.
func (lrq *LoginResetQuery) Offset(offset int) *LoginResetQuery {
	lrq.ctx.Offset = &offset
	return lrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lrq *LoginResetQuery) Unique(unique bool) *LoginResetQuery {
	lrq.ctx.Unique = &unique
	return lrq
}

// Order specifies how the records should be ordered.
func (lrq *LoginResetQuery) Order(o ...loginreset.OrderOption) *LoginResetQuery {
	lrq.order = append(lrq.order, o...)
	return lrq
}

// QueryNotes chains the current query on the "notes" edge.
func (lrq *LoginResetQuery) QueryNotes() *NoteQuery {
	query := (&NoteClient{config: lrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(loginreset.Table, loginreset.FieldID, selector),
			sqlgraph.To(note.Table, note.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, loginreset.NotesTable, loginreset.NotesColumn),
		)
		fromU = sqlgraph.SetNeighbors(lrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLogin chains the current query on the "login" edge.
func (lrq *LoginResetQuery) QueryLogin() *LoginQuery {
	query := (&LoginClient{config: lrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(loginreset.Table, loginreset.FieldID, selector),
			sqlgraph.To(login.Table, login.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, loginreset.LoginTable, loginreset.LoginColumn),
		)
		fromU = sqlgraph.SetNeighbors(lrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LoginReset entity from the query.
// Returns a *NotFoundError when no LoginReset was found.
func (lrq *LoginResetQuery) First(ctx context.Context) (*LoginReset, error) {
	nodes, err := lrq.Limit(1).All(setContextOp(ctx, lrq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{loginreset.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lrq *LoginResetQuery) FirstX(ctx context.Context) *LoginReset {
	node, err := lrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LoginReset ID from the query.
// Returns a *NotFoundError when no LoginReset ID was found.
func (lrq *LoginResetQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lrq.Limit(1).IDs(setContextOp(ctx, lrq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{loginreset.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lrq *LoginResetQuery) FirstIDX(ctx context.Context) int {
	id, err := lrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LoginReset entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LoginReset entity is found.
// Returns a *NotFoundError when no LoginReset entities are found.
func (lrq *LoginResetQuery) Only(ctx context.Context) (*LoginReset, error) {
	nodes, err := lrq.Limit(2).All(setContextOp(ctx, lrq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{loginreset.Label}
	default:
		return nil, &NotSingularError{loginreset.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lrq *LoginResetQuery) OnlyX(ctx context.Context) *LoginReset {
	node, err := lrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LoginReset ID in the query.
// Returns a *NotSingularError when more than one LoginReset ID is found.
// Returns a *NotFoundError when no entities are found.
func (lrq *LoginResetQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lrq.Limit(2).IDs(setContextOp(ctx, lrq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{loginreset.Label}
	default:
		err = &NotSingularError{loginreset.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lrq *LoginResetQuery) OnlyIDX(ctx context.Context) int {
	id, err := lrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LoginResets.
func (lrq *LoginResetQuery) All(ctx context.Context) ([]*LoginReset, error) {
	ctx = setContextOp(ctx, lrq.ctx, "All")
	if err := lrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LoginReset, *LoginResetQuery]()
	return withInterceptors[[]*LoginReset](ctx, lrq, qr, lrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lrq *LoginResetQuery) AllX(ctx context.Context) []*LoginReset {
	nodes, err := lrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LoginReset IDs.
func (lrq *LoginResetQuery) IDs(ctx context.Context) (ids []int, err error) {
	if lrq.ctx.Unique == nil && lrq.path != nil {
		lrq.Unique(true)
	}
	ctx = setContextOp(ctx, lrq.ctx, "IDs")
	if err = lrq.Select(loginreset.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lrq *LoginResetQuery) IDsX(ctx context.Context) []int {
	ids, err := lrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lrq *LoginResetQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lrq.ctx, "Count")
	if err := lrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lrq, querierCount[*LoginResetQuery](), lrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lrq *LoginResetQuery) CountX(ctx context.Context) int {
	count, err := lrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lrq *LoginResetQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lrq.ctx, "Exist")
	switch _, err := lrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lrq *LoginResetQuery) ExistX(ctx context.Context) bool {
	exist, err := lrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LoginResetQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lrq *LoginResetQuery) Clone() *LoginResetQuery {
	if lrq == nil {
		return nil
	}
	return &LoginResetQuery{
		config:     lrq.config,
		ctx:        lrq.ctx.Clone(),
		order:      append([]loginreset.OrderOption{}, lrq.order...),
		inters:     append([]Interceptor{}, lrq.inters...),
		predicates: append([]predicate.LoginReset{}, lrq.predicates...),
		withNotes:  lrq.withNotes.Clone(),
		withLogin:  lrq.withLogin.Clone(),
		// clone intermediate query.
		sql:  lrq.sql.Clone(),
		path: lrq.path,
	}
}

// WithNotes tells the query-builder to eager-load the nodes that are connected to
// the "notes" edge. The optional arguments are used to configure the query builder of the edge.
func (lrq *LoginResetQuery) WithNotes(opts ...func(*NoteQuery)) *LoginResetQuery {
	query := (&NoteClient{config: lrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lrq.withNotes = query
	return lrq
}

// WithLogin tells the query-builder to eager-load the nodes that are connected to
// the "login" edge. The optional arguments are used to configure the query builder of the edge.
func (lrq *LoginResetQuery) WithLogin(opts ...func(*LoginQuery)) *LoginResetQuery {
	query := (&LoginClient{config: lrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lrq.withLogin = query
	return lrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Token string `json:"token,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LoginReset.Query().
//		GroupBy(loginreset.FieldToken).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lrq *LoginResetQuery) GroupBy(field string, fields ...string) *LoginResetGroupBy {
	lrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LoginResetGroupBy{build: lrq}
	grbuild.flds = &lrq.ctx.Fields
	grbuild.label = loginreset.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Token string `json:"token,omitempty"`
//	}
//
//	client.LoginReset.Query().
//		Select(loginreset.FieldToken).
//		Scan(ctx, &v)
func (lrq *LoginResetQuery) Select(fields ...string) *LoginResetSelect {
	lrq.ctx.Fields = append(lrq.ctx.Fields, fields...)
	sbuild := &LoginResetSelect{LoginResetQuery: lrq}
	sbuild.label = loginreset.Label
	sbuild.flds, sbuild.scan = &lrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LoginResetSelect configured with the given aggregations.
func (lrq *LoginResetQuery) Aggregate(fns ...AggregateFunc) *LoginResetSelect {
	return lrq.Select().Aggregate(fns...)
}

func (lrq *LoginResetQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lrq); err != nil {
				return err
			}
		}
	}
	for _, f := range lrq.ctx.Fields {
		if !loginreset.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lrq.path != nil {
		prev, err := lrq.path(ctx)
		if err != nil {
			return err
		}
		lrq.sql = prev
	}
	return nil
}

func (lrq *LoginResetQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LoginReset, error) {
	var (
		nodes       = []*LoginReset{}
		withFKs     = lrq.withFKs
		_spec       = lrq.querySpec()
		loadedTypes = [2]bool{
			lrq.withNotes != nil,
			lrq.withLogin != nil,
		}
	)
	if lrq.withLogin != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, loginreset.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LoginReset).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LoginReset{config: lrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lrq.withNotes; query != nil {
		if err := lrq.loadNotes(ctx, query, nodes,
			func(n *LoginReset) { n.Edges.Notes = []*Note{} },
			func(n *LoginReset, e *Note) { n.Edges.Notes = append(n.Edges.Notes, e) }); err != nil {
			return nil, err
		}
	}
	if query := lrq.withLogin; query != nil {
		if err := lrq.loadLogin(ctx, query, nodes, nil,
			func(n *LoginReset, e *Login) { n.Edges.Login = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lrq *LoginResetQuery) loadNotes(ctx context.Context, query *NoteQuery, nodes []*LoginReset, init func(*LoginReset), assign func(*LoginReset, *Note)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*LoginReset)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Note(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(loginreset.NotesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.login_reset_notes
		if fk == nil {
			return fmt.Errorf(`foreign-key "login_reset_notes" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "login_reset_notes" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (lrq *LoginResetQuery) loadLogin(ctx context.Context, query *LoginQuery, nodes []*LoginReset, init func(*LoginReset), assign func(*LoginReset, *Login)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*LoginReset)
	for i := range nodes {
		if nodes[i].login_login_resets == nil {
			continue
		}
		fk := *nodes[i].login_login_resets
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(login.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "login_login_resets" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (lrq *LoginResetQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lrq.querySpec()
	_spec.Node.Columns = lrq.ctx.Fields
	if len(lrq.ctx.Fields) > 0 {
		_spec.Unique = lrq.ctx.Unique != nil && *lrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lrq.driver, _spec)
}

func (lrq *LoginResetQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(loginreset.Table, loginreset.Columns, sqlgraph.NewFieldSpec(loginreset.FieldID, field.TypeInt))
	_spec.From = lrq.sql
	if unique := lrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lrq.path != nil {
		_spec.Unique = true
	}
	if fields := lrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginreset.FieldID)
		for i := range fields {
			if fields[i] != loginreset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lrq *LoginResetQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lrq.driver.Dialect())
	t1 := builder.Table(loginreset.Table)
	columns := lrq.ctx.Fields
	if len(columns) == 0 {
		columns = loginreset.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lrq.sql != nil {
		selector = lrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lrq.ctx.Unique != nil && *lrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lrq.predicates {
		p(selector)
	}
	for _, p := range lrq.order {
		p(selector)
	}
	if offset := lrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LoginResetGroupBy is the group-by builder for LoginReset entities.
type LoginResetGroupBy struct {
	selector
	build *LoginResetQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lrgb *LoginResetGroupBy) Aggregate(fns ...AggregateFunc) *LoginResetGroupBy {
	lrgb.fns = append(lrgb.fns, fns...)
	return lrgb
}

// Scan applies the selector query and scans the result into the given value.
func (lrgb *LoginResetGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lrgb.build.ctx, "GroupBy")
	if err := lrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LoginResetQuery, *LoginResetGroupBy](ctx, lrgb.build, lrgb, lrgb.build.inters, v)
}

func (lrgb *LoginResetGroupBy) sqlScan(ctx context.Context, root *LoginResetQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lrgb.fns))
	for _, fn := range lrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lrgb.flds)+len(lrgb.fns))
		for _, f := range *lrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LoginResetSelect is the builder for selecting fields of LoginReset entities.
type LoginResetSelect struct {
	*LoginResetQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lrs *LoginResetSelect) Aggregate(fns ...AggregateFunc) *LoginResetSelect {
	lrs.fns = append(lrs.fns, fns...)
	return lrs
}

// Scan applies the selector query and scans the result into the given value.
func (lrs *LoginResetSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lrs.ctx, "Select")
	if err := lrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LoginResetQuery, *LoginResetSelect](ctx, lrs.LoginResetQuery, lrs, lrs.inters, v)
}

func (lrs *LoginResetSelect) sqlScan(ctx context.Context, root *LoginResetQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lrs.fns))
	for _, fn := range lrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
