// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/derfinlay/basecrm/ent/customer"
	"github.com/derfinlay/basecrm/ent/login"
	"github.com/derfinlay/basecrm/ent/loginreset"
	"github.com/derfinlay/basecrm/ent/note"
	"github.com/derfinlay/basecrm/ent/predicate"
)

// LoginUpdate is the builder for updating Login entities.
type LoginUpdate struct {
	config
	hooks    []Hook
	mutation *LoginMutation
}

// Where appends a list predicates to the LoginUpdate builder.
func (lu *LoginUpdate) Where(ps ...predicate.Login) *LoginUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetPassword sets the "password" field.
func (lu *LoginUpdate) SetPassword(s string) *LoginUpdate {
	lu.mutation.SetPassword(s)
	return lu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (lu *LoginUpdate) SetNillablePassword(s *string) *LoginUpdate {
	if s != nil {
		lu.SetPassword(*s)
	}
	return lu
}

// SetEmail sets the "email" field.
func (lu *LoginUpdate) SetEmail(s string) *LoginUpdate {
	lu.mutation.SetEmail(s)
	return lu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (lu *LoginUpdate) SetNillableEmail(s *string) *LoginUpdate {
	if s != nil {
		lu.SetEmail(*s)
	}
	return lu
}

// SetLastLogin sets the "last_login" field.
func (lu *LoginUpdate) SetLastLogin(t time.Time) *LoginUpdate {
	lu.mutation.SetLastLogin(t)
	return lu
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (lu *LoginUpdate) SetNillableLastLogin(t *time.Time) *LoginUpdate {
	if t != nil {
		lu.SetLastLogin(*t)
	}
	return lu
}

// SetUpdatedAt sets the "updated_at" field.
func (lu *LoginUpdate) SetUpdatedAt(t time.Time) *LoginUpdate {
	lu.mutation.SetUpdatedAt(t)
	return lu
}

// SetCustomerID sets the "customer" edge to the Customer entity by ID.
func (lu *LoginUpdate) SetCustomerID(id int) *LoginUpdate {
	lu.mutation.SetCustomerID(id)
	return lu
}

// SetNillableCustomerID sets the "customer" edge to the Customer entity by ID if the given value is not nil.
func (lu *LoginUpdate) SetNillableCustomerID(id *int) *LoginUpdate {
	if id != nil {
		lu = lu.SetCustomerID(*id)
	}
	return lu
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (lu *LoginUpdate) SetCustomer(c *Customer) *LoginUpdate {
	return lu.SetCustomerID(c.ID)
}

// AddLoginResetIDs adds the "login_resets" edge to the LoginReset entity by IDs.
func (lu *LoginUpdate) AddLoginResetIDs(ids ...int) *LoginUpdate {
	lu.mutation.AddLoginResetIDs(ids...)
	return lu
}

// AddLoginResets adds the "login_resets" edges to the LoginReset entity.
func (lu *LoginUpdate) AddLoginResets(l ...*LoginReset) *LoginUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return lu.AddLoginResetIDs(ids...)
}

// AddNoteIDs adds the "notes" edge to the Note entity by IDs.
func (lu *LoginUpdate) AddNoteIDs(ids ...int) *LoginUpdate {
	lu.mutation.AddNoteIDs(ids...)
	return lu
}

// AddNotes adds the "notes" edges to the Note entity.
func (lu *LoginUpdate) AddNotes(n ...*Note) *LoginUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return lu.AddNoteIDs(ids...)
}

// Mutation returns the LoginMutation object of the builder.
func (lu *LoginUpdate) Mutation() *LoginMutation {
	return lu.mutation
}

// ClearCustomer clears the "customer" edge to the Customer entity.
func (lu *LoginUpdate) ClearCustomer() *LoginUpdate {
	lu.mutation.ClearCustomer()
	return lu
}

// ClearLoginResets clears all "login_resets" edges to the LoginReset entity.
func (lu *LoginUpdate) ClearLoginResets() *LoginUpdate {
	lu.mutation.ClearLoginResets()
	return lu
}

// RemoveLoginResetIDs removes the "login_resets" edge to LoginReset entities by IDs.
func (lu *LoginUpdate) RemoveLoginResetIDs(ids ...int) *LoginUpdate {
	lu.mutation.RemoveLoginResetIDs(ids...)
	return lu
}

// RemoveLoginResets removes "login_resets" edges to LoginReset entities.
func (lu *LoginUpdate) RemoveLoginResets(l ...*LoginReset) *LoginUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return lu.RemoveLoginResetIDs(ids...)
}

// ClearNotes clears all "notes" edges to the Note entity.
func (lu *LoginUpdate) ClearNotes() *LoginUpdate {
	lu.mutation.ClearNotes()
	return lu
}

// RemoveNoteIDs removes the "notes" edge to Note entities by IDs.
func (lu *LoginUpdate) RemoveNoteIDs(ids ...int) *LoginUpdate {
	lu.mutation.RemoveNoteIDs(ids...)
	return lu
}

// RemoveNotes removes "notes" edges to Note entities.
func (lu *LoginUpdate) RemoveNotes(n ...*Note) *LoginUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return lu.RemoveNoteIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LoginUpdate) Save(ctx context.Context) (int, error) {
	lu.defaults()
	return withHooks(ctx, lu.sqlSave, lu.mutation, lu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LoginUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LoginUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LoginUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lu *LoginUpdate) defaults() {
	if _, ok := lu.mutation.UpdatedAt(); !ok {
		v := login.UpdateDefaultUpdatedAt()
		lu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lu *LoginUpdate) check() error {
	if v, ok := lu.mutation.Password(); ok {
		if err := login.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Login.password": %w`, err)}
		}
	}
	if v, ok := lu.mutation.Email(); ok {
		if err := login.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Login.email": %w`, err)}
		}
	}
	return nil
}

func (lu *LoginUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := lu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(login.Table, login.Columns, sqlgraph.NewFieldSpec(login.FieldID, field.TypeInt))
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.Password(); ok {
		_spec.SetField(login.FieldPassword, field.TypeString, value)
	}
	if value, ok := lu.mutation.Email(); ok {
		_spec.SetField(login.FieldEmail, field.TypeString, value)
	}
	if value, ok := lu.mutation.LastLogin(); ok {
		_spec.SetField(login.FieldLastLogin, field.TypeTime, value)
	}
	if value, ok := lu.mutation.UpdatedAt(); ok {
		_spec.SetField(login.FieldUpdatedAt, field.TypeTime, value)
	}
	if lu.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   login.CustomerTable,
			Columns: []string{login.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   login.CustomerTable,
			Columns: []string{login.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lu.mutation.LoginResetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   login.LoginResetsTable,
			Columns: []string{login.LoginResetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginreset.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.RemovedLoginResetsIDs(); len(nodes) > 0 && !lu.mutation.LoginResetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   login.LoginResetsTable,
			Columns: []string{login.LoginResetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginreset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.LoginResetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   login.LoginResetsTable,
			Columns: []string{login.LoginResetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginreset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lu.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   login.NotesTable,
			Columns: []string{login.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.RemovedNotesIDs(); len(nodes) > 0 && !lu.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   login.NotesTable,
			Columns: []string{login.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.NotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   login.NotesTable,
			Columns: []string{login.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{login.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lu.mutation.done = true
	return n, nil
}

// LoginUpdateOne is the builder for updating a single Login entity.
type LoginUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LoginMutation
}

// SetPassword sets the "password" field.
func (luo *LoginUpdateOne) SetPassword(s string) *LoginUpdateOne {
	luo.mutation.SetPassword(s)
	return luo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (luo *LoginUpdateOne) SetNillablePassword(s *string) *LoginUpdateOne {
	if s != nil {
		luo.SetPassword(*s)
	}
	return luo
}

// SetEmail sets the "email" field.
func (luo *LoginUpdateOne) SetEmail(s string) *LoginUpdateOne {
	luo.mutation.SetEmail(s)
	return luo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (luo *LoginUpdateOne) SetNillableEmail(s *string) *LoginUpdateOne {
	if s != nil {
		luo.SetEmail(*s)
	}
	return luo
}

// SetLastLogin sets the "last_login" field.
func (luo *LoginUpdateOne) SetLastLogin(t time.Time) *LoginUpdateOne {
	luo.mutation.SetLastLogin(t)
	return luo
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (luo *LoginUpdateOne) SetNillableLastLogin(t *time.Time) *LoginUpdateOne {
	if t != nil {
		luo.SetLastLogin(*t)
	}
	return luo
}

// SetUpdatedAt sets the "updated_at" field.
func (luo *LoginUpdateOne) SetUpdatedAt(t time.Time) *LoginUpdateOne {
	luo.mutation.SetUpdatedAt(t)
	return luo
}

// SetCustomerID sets the "customer" edge to the Customer entity by ID.
func (luo *LoginUpdateOne) SetCustomerID(id int) *LoginUpdateOne {
	luo.mutation.SetCustomerID(id)
	return luo
}

// SetNillableCustomerID sets the "customer" edge to the Customer entity by ID if the given value is not nil.
func (luo *LoginUpdateOne) SetNillableCustomerID(id *int) *LoginUpdateOne {
	if id != nil {
		luo = luo.SetCustomerID(*id)
	}
	return luo
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (luo *LoginUpdateOne) SetCustomer(c *Customer) *LoginUpdateOne {
	return luo.SetCustomerID(c.ID)
}

// AddLoginResetIDs adds the "login_resets" edge to the LoginReset entity by IDs.
func (luo *LoginUpdateOne) AddLoginResetIDs(ids ...int) *LoginUpdateOne {
	luo.mutation.AddLoginResetIDs(ids...)
	return luo
}

// AddLoginResets adds the "login_resets" edges to the LoginReset entity.
func (luo *LoginUpdateOne) AddLoginResets(l ...*LoginReset) *LoginUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return luo.AddLoginResetIDs(ids...)
}

// AddNoteIDs adds the "notes" edge to the Note entity by IDs.
func (luo *LoginUpdateOne) AddNoteIDs(ids ...int) *LoginUpdateOne {
	luo.mutation.AddNoteIDs(ids...)
	return luo
}

// AddNotes adds the "notes" edges to the Note entity.
func (luo *LoginUpdateOne) AddNotes(n ...*Note) *LoginUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return luo.AddNoteIDs(ids...)
}

// Mutation returns the LoginMutation object of the builder.
func (luo *LoginUpdateOne) Mutation() *LoginMutation {
	return luo.mutation
}

// ClearCustomer clears the "customer" edge to the Customer entity.
func (luo *LoginUpdateOne) ClearCustomer() *LoginUpdateOne {
	luo.mutation.ClearCustomer()
	return luo
}

// ClearLoginResets clears all "login_resets" edges to the LoginReset entity.
func (luo *LoginUpdateOne) ClearLoginResets() *LoginUpdateOne {
	luo.mutation.ClearLoginResets()
	return luo
}

// RemoveLoginResetIDs removes the "login_resets" edge to LoginReset entities by IDs.
func (luo *LoginUpdateOne) RemoveLoginResetIDs(ids ...int) *LoginUpdateOne {
	luo.mutation.RemoveLoginResetIDs(ids...)
	return luo
}

// RemoveLoginResets removes "login_resets" edges to LoginReset entities.
func (luo *LoginUpdateOne) RemoveLoginResets(l ...*LoginReset) *LoginUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return luo.RemoveLoginResetIDs(ids...)
}

// ClearNotes clears all "notes" edges to the Note entity.
func (luo *LoginUpdateOne) ClearNotes() *LoginUpdateOne {
	luo.mutation.ClearNotes()
	return luo
}

// RemoveNoteIDs removes the "notes" edge to Note entities by IDs.
func (luo *LoginUpdateOne) RemoveNoteIDs(ids ...int) *LoginUpdateOne {
	luo.mutation.RemoveNoteIDs(ids...)
	return luo
}

// RemoveNotes removes "notes" edges to Note entities.
func (luo *LoginUpdateOne) RemoveNotes(n ...*Note) *LoginUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return luo.RemoveNoteIDs(ids...)
}

// Where appends a list predicates to the LoginUpdate builder.
func (luo *LoginUpdateOne) Where(ps ...predicate.Login) *LoginUpdateOne {
	luo.mutation.Where(ps...)
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LoginUpdateOne) Select(field string, fields ...string) *LoginUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Login entity.
func (luo *LoginUpdateOne) Save(ctx context.Context) (*Login, error) {
	luo.defaults()
	return withHooks(ctx, luo.sqlSave, luo.mutation, luo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LoginUpdateOne) SaveX(ctx context.Context) *Login {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LoginUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LoginUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (luo *LoginUpdateOne) defaults() {
	if _, ok := luo.mutation.UpdatedAt(); !ok {
		v := login.UpdateDefaultUpdatedAt()
		luo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (luo *LoginUpdateOne) check() error {
	if v, ok := luo.mutation.Password(); ok {
		if err := login.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Login.password": %w`, err)}
		}
	}
	if v, ok := luo.mutation.Email(); ok {
		if err := login.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Login.email": %w`, err)}
		}
	}
	return nil
}

func (luo *LoginUpdateOne) sqlSave(ctx context.Context) (_node *Login, err error) {
	if err := luo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(login.Table, login.Columns, sqlgraph.NewFieldSpec(login.FieldID, field.TypeInt))
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Login.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, login.FieldID)
		for _, f := range fields {
			if !login.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != login.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.Password(); ok {
		_spec.SetField(login.FieldPassword, field.TypeString, value)
	}
	if value, ok := luo.mutation.Email(); ok {
		_spec.SetField(login.FieldEmail, field.TypeString, value)
	}
	if value, ok := luo.mutation.LastLogin(); ok {
		_spec.SetField(login.FieldLastLogin, field.TypeTime, value)
	}
	if value, ok := luo.mutation.UpdatedAt(); ok {
		_spec.SetField(login.FieldUpdatedAt, field.TypeTime, value)
	}
	if luo.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   login.CustomerTable,
			Columns: []string{login.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   login.CustomerTable,
			Columns: []string{login.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if luo.mutation.LoginResetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   login.LoginResetsTable,
			Columns: []string{login.LoginResetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginreset.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.RemovedLoginResetsIDs(); len(nodes) > 0 && !luo.mutation.LoginResetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   login.LoginResetsTable,
			Columns: []string{login.LoginResetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginreset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.LoginResetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   login.LoginResetsTable,
			Columns: []string{login.LoginResetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginreset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if luo.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   login.NotesTable,
			Columns: []string{login.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.RemovedNotesIDs(); len(nodes) > 0 && !luo.mutation.NotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   login.NotesTable,
			Columns: []string{login.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.NotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   login.NotesTable,
			Columns: []string{login.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Login{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{login.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	luo.mutation.done = true
	return _node, nil
}
