// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/derfinlay/basecrm/ent/customer"
	"github.com/derfinlay/basecrm/ent/login"
)

// Login is the model entity for the Login schema.
type Login struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"password,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// LastLogin holds the value of the "last_login" field.
	LastLogin time.Time `json:"last_login,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LoginQuery when eager-loading is set.
	Edges          LoginEdges `json:"edges"`
	customer_login *int
	selectValues   sql.SelectValues
}

// LoginEdges holds the relations/edges for other nodes in the graph.
type LoginEdges struct {
	// Customer holds the value of the customer edge.
	Customer *Customer `json:"customer,omitempty"`
	// LoginResets holds the value of the login_resets edge.
	LoginResets []*LoginReset `json:"login_resets,omitempty"`
	// Notes holds the value of the notes edge.
	Notes []*Note `json:"notes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// CustomerOrErr returns the Customer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LoginEdges) CustomerOrErr() (*Customer, error) {
	if e.loadedTypes[0] {
		if e.Customer == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: customer.Label}
		}
		return e.Customer, nil
	}
	return nil, &NotLoadedError{edge: "customer"}
}

// LoginResetsOrErr returns the LoginResets value or an error if the edge
// was not loaded in eager-loading.
func (e LoginEdges) LoginResetsOrErr() ([]*LoginReset, error) {
	if e.loadedTypes[1] {
		return e.LoginResets, nil
	}
	return nil, &NotLoadedError{edge: "login_resets"}
}

// NotesOrErr returns the Notes value or an error if the edge
// was not loaded in eager-loading.
func (e LoginEdges) NotesOrErr() ([]*Note, error) {
	if e.loadedTypes[2] {
		return e.Notes, nil
	}
	return nil, &NotLoadedError{edge: "notes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Login) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case login.FieldID:
			values[i] = new(sql.NullInt64)
		case login.FieldPassword, login.FieldEmail:
			values[i] = new(sql.NullString)
		case login.FieldLastLogin, login.FieldCreatedAt, login.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case login.ForeignKeys[0]: // customer_login
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Login fields.
func (l *Login) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case login.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			l.ID = int(value.Int64)
		case login.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				l.Password = value.String
			}
		case login.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				l.Email = value.String
			}
		case login.FieldLastLogin:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_login", values[i])
			} else if value.Valid {
				l.LastLogin = value.Time
			}
		case login.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				l.CreatedAt = value.Time
			}
		case login.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				l.UpdatedAt = value.Time
			}
		case login.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field customer_login", value)
			} else if value.Valid {
				l.customer_login = new(int)
				*l.customer_login = int(value.Int64)
			}
		default:
			l.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Login.
// This includes values selected through modifiers, order, etc.
func (l *Login) Value(name string) (ent.Value, error) {
	return l.selectValues.Get(name)
}

// QueryCustomer queries the "customer" edge of the Login entity.
func (l *Login) QueryCustomer() *CustomerQuery {
	return NewLoginClient(l.config).QueryCustomer(l)
}

// QueryLoginResets queries the "login_resets" edge of the Login entity.
func (l *Login) QueryLoginResets() *LoginResetQuery {
	return NewLoginClient(l.config).QueryLoginResets(l)
}

// QueryNotes queries the "notes" edge of the Login entity.
func (l *Login) QueryNotes() *NoteQuery {
	return NewLoginClient(l.config).QueryNotes(l)
}

// Update returns a builder for updating this Login.
// Note that you need to call Login.Unwrap() before calling this method if this Login
// was returned from a transaction, and the transaction was committed or rolled back.
func (l *Login) Update() *LoginUpdateOne {
	return NewLoginClient(l.config).UpdateOne(l)
}

// Unwrap unwraps the Login entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (l *Login) Unwrap() *Login {
	_tx, ok := l.config.driver.(*txDriver)
	if !ok {
		panic("ent: Login is not a transactional entity")
	}
	l.config.driver = _tx.drv
	return l
}

// String implements the fmt.Stringer.
func (l *Login) String() string {
	var builder strings.Builder
	builder.WriteString("Login(")
	builder.WriteString(fmt.Sprintf("id=%v, ", l.ID))
	builder.WriteString("password=")
	builder.WriteString(l.Password)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(l.Email)
	builder.WriteString(", ")
	builder.WriteString("last_login=")
	builder.WriteString(l.LastLogin.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(l.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(l.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Logins is a parsable slice of Login.
type Logins []*Login
