// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BillingAddress is the predicate function for billingaddress builders.
type BillingAddress func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// DeliveryAddress is the predicate function for deliveryaddress builders.
type DeliveryAddress func(*sql.Selector)

// Login is the predicate function for login builders.
type Login func(*sql.Selector)

// LoginReset is the predicate function for loginreset builders.
type LoginReset func(*sql.Selector)

// Note is the predicate function for note builders.
type Note func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Tel is the predicate function for tel builders.
type Tel func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserSession is the predicate function for usersession builders.
type UserSession func(*sql.Selector)
